### ISSUE TITLE
RFE: Move Dockerfile to project top level

### ISSUE THREAD

**Issue by scop** [Perl-Critic/Perl-Critic#999]
Nice to see a Dockerfile being added.

However, it's customary to ship Dockerfiles at project top level, and some software actually depends on things being set up that way, and people tend to expect to find it there, too.

My use case is pre-commit and its `docker` "language" support. The only way that works is with a top level Dockerfile: https://pre-commit.com/#docker

If Perl-Critic's Dockerfile would be moved, I could add support for it in my pre-commit-perlcritic hook at https://github.com/scop/pre-commit-perlcritic. A dependency on Perl isn't usually a big deal in setups where perlcritic is to be run, but it would be nice to provide the option using the Docker flavor.

**Comment by petdance** [comment]
Please tell more about this. I added the Dockerfile because someone suggested it, but I put it in extras so it was clear that it wasn't something that we were officially supporting.

What does pre-commit do? Does it build a Docker container for every commit you make and then run it? Do you have to have a Perl-Critic tarball that it builds from?

**Comment by scop** [comment]
Actually, this was a thinko on my part. What's requested here would be doable only if the actual pre-commit hook configuration would reside in the same repo as the Dockerfile. So either the pre-commit hook config would have to reside here, or my repo would have to have the Dockerfile. The former was discussed and rejected in #903, and doing the latter isn't something I think I'll be doing.

What I _could_ make use in of the config residing in my separate repo would be a readily built, official perlcritic Docker image from a public repository such as the GitHub Container Registry, or Docker Hub. I'll do that if the image ever becomes available.

Anyway, I'll close this issue because the RFE is misguided because of the above. I'll include the bits I wrote about how pre-commit works below, before I realized the the brokenness of the request while writing the reply.

---

pre-commit builds the Docker image once, when first time invoking the pre-commit hook with a config containing it. The image will be reused indefinitely for subsequent runs, as long as the version stays the same in the pre-commit config, or the user explicitly purges the image or "gc"'s the pre-commit config.

The Perl-Critic tarball is not required for the Docker-based config, pre-commit uses the project Dockerfile here as-is to build the image.

**Comment by petdance** [comment]
>  So either the pre-commit hook config would have to reside here, or my repo would have to have the Dockerfile.

Isn't the pre-commit hook config something that's user-specific? That was what I thought and now I'm looking back at #903 and maybe I was wrong?

>  a readily built, official perlcritic Docker image from a public repository such as the GitHub Container Registry, or Docker Hub.

Maybe it's time to do a Docker image. Let's discuss. I'd prefer chat somewhere, but this will do as well.

**Comment by petdance** [comment]
Looks like problem #1 with doing an image is that Docker images need to be all lowercase and we would have to change the organization and project name.

I'm not opposed, just making notes.

**Comment by scop** [comment]
The terminology is somewhat confusing, and the word "config" is kind of overloaded, but a pre-commit tool setup consists of two configuration files: 
1) `.pre-commit-hooks.yaml` which defines how the hook works. This is located **in the repo providing the hook**, often the same repo that hosts the tool the hook uses. Documentation at https://pre-commit.com/#creating-new-hooks, example from my repo currently providing the perlcritic hook: https://github.com/scop/pre-commit-perlcritic/blob/main/.pre-commit-hooks.yaml (this would look somewhat different if it was located here in this repo, we can discuss that later if we get that far)
2) `.pre-commit-config.yaml` is created by the pre-commit user **in their repo**. It specifies what hooks to use, what versions of them, and some optional configuration overrides (e.g. different command line arguments, additional packages to install, etc). Documentation at https://pre-commit.com/#adding-pre-commit-plugins-to-your-project, example from a repo that uses the hook from the above mentioned my pre-commit-perlcritic "hook" repo: https://github.com/scop/bash-completion/blob/a392580b846eaeff58668db9dc0a3e410ab8216d/.pre-commit-config.yaml#L105-L111

**Comment by scop** [comment]
I don't think there's a need to change the organization/project names, they are case insensitive in GitHub as far as I know. For example https://github.com/perl-critic/perl-critic works, I'd assume `ghcr.io/perl-critic/perl-critic` would work as the image too.

**Comment by scop** [comment]
Wrt chat vs this issue, perhaps GitHub Discussions? https://docs.github.com/en/discussions (they're not a chat either though, but JFYI just in case).

**Comment by scop** [comment]
A GitHub workflow to build and push the Docker image on releases to ghcr.io could look something like this:
```yaml
name: "Docker image"

on:
  push:
    tags:
      - "^v[0-9]+.[0-9]+$"

jobs:
  docker-image:
    runs-on: "ubuntu-latest"
    if: "github.repository_owner == 'Perl-Critic' && github.ref == 'refs/heads/master'"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "docker/setup-qemu-action@v2"
      - uses: "docker/setup-buildx-action@v2"
      - uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - uses: "docker/build-push-action@v3"
        with:
          file: "extra/Dockerfile"
          platforms: "linux/amd64,linux/arm64"
          tags: "ghcr.io/perl-critic/perl-critic:${{ github.ref_name }}"
          push: true
```
